// Build a terse, review-ready Markdown comment for a pull request from the
// report produced by the capture pipeline. It summarizes verdicts and, when
// image URLs are supplied, embeds the side-by-side evidence inline.

const VERDICT_LABEL = {
  unchanged: 'unchanged',
  'changed-within-threshold': 'changed (within threshold)',
  'review-required': 'review-required',
  'capture-failed': 'capture failed',
};

import { diagramSection } from './backend.mjs';

export function buildPrComment(report, pr, images = null, diagram = null, notes = null) {
  const baseShort = report.base.sha.slice(0, 7);
  const headShort = report.head.sha.slice(0, 7);
  const lines = [];

  lines.push('## Visual review');
  lines.push('');
  lines.push(`**${pr.title}** \`${pr.baseRef}\` (\`${baseShort}\`) -> \`${pr.headRef}\` (\`${headShort}\`)`);
  lines.push('');
  const noteText = notes ? String(notes).trim() : '';
  if (noteText) {
    lines.push(noteText);
    lines.push('');
  }
  const sequence = diagramSection(diagram);
  if (sequence) {
    lines.push(sequence);
    lines.push('');
  }
  lines.push('| Scenario | Viewport | Verdict |');
  lines.push('| --- | --- | --- |');
  for (const cell of report.cells) {
    lines.push(`| ${cell.scenarioName} | ${cell.viewport} | ${VERDICT_LABEL[cell.verdict] ?? cell.verdict} |`);
  }
  lines.push('');

  const attention = report.cells.filter(
    (cell) => cell.verdict === 'review-required' || cell.verdict === 'capture-failed',
  );
  if (attention.length > 0) {
    lines.push('**Needs attention**');
    for (const cell of attention) {
      const reason = cell.reasons && cell.reasons[0] ? `: ${cell.reasons[0]}` : '';
      lines.push(`- \`${cell.scenarioName} @ ${cell.viewport}\` - ${VERDICT_LABEL[cell.verdict]}${reason}`);
    }
    lines.push('');
  }

  if (report.skippedScenarios && report.skippedScenarios.length > 0) {
    lines.push(`Skipped: ${report.skippedScenarios.map((scenario) => scenario.name).join(', ')}.`);
    lines.push('');
  }

  if (images && Object.keys(images).length > 0) {
    lines.push('## Evidence');
    lines.push('');
    for (const cell of report.cells) {
      const url = images[`${cell.scenarioId}--${cell.viewport}`];
      if (url) {
        lines.push(`### ${cell.scenarioName} @ ${cell.viewport}`);
        lines.push('');
        lines.push(`![${cell.scenarioName} ${cell.viewport}](${url})`);
        lines.push('');
      }
    }
  }

  lines.push(
    images
      ? '> Generated by `visual-pr-review`. Verdicts summarize the evidence; side-by-side images are embedded above.'
      : '> Generated by `visual-pr-review`. Verdicts summarize the evidence; the side-by-side and diff images live in the local output directory and are not embedded here.',
  );
  return lines.join('\n');
}
